Repository KubeJS-Mods/KubeJS, pull requests merged in 2022-06, with the labels that each got.

#376 Add click events to some chat outputs for ease of use
  common/src/main/java/dev/latvian/mods/kubejs/command/KubeJSCommands.java
  common/src/main/java/dev/latvian/mods/kubejs/core/LootTablesKJS.java
  common/src/main/java/dev/latvian/mods/kubejs/player/KubeJSPlayerEventHandler.java
Labels: small change

#380 Fixed #378
  common/src/main/java/dev/latvian/mods/kubejs/misc/MobEffectBuilder.java
Labels: 1.18, small change, 1.19

#386 Attribute modification support
  common/src/main/java/dev/latvian/mods/kubejs/core/ModifiableItemKJS.java
  common/src/main/java/dev/latvian/mods/kubejs/item/ItemModificationProperties.java
  common/src/main/java/dev/latvian/mods/kubejs/mixin/common/tools/ArmorItemMixin.java
  common/src/main/java/dev/latvian/mods/kubejs/mixin/common/tools/DiggerItemMixin.java
  common/src/main/java/dev/latvian/mods/kubejs/mixin/common/tools/SwordItemMixin.java
  common/src/main/java/dev/latvian/mods/kubejs/mixin/common/tools/TridentItemMixin.java
  common/src/main/resources/kubejs-common.mixins.json
  common/src/main/resources/kubejs.accesswidener
Labels: enhancement, last call, priority: medium, new feature, 1.18, 1.19
