Repository KubeJS-Mods/KubeJS, pull requests merged in 2022-04, with the labels that each got.

#308 Attribute modifying and effect tick support for MobEffectBuilder
  common/src/main/java/dev/latvian/mods/kubejs/KubeJSRegistries.java
  common/src/main/java/dev/latvian/mods/kubejs/misc/BasicMobEffect.java
  common/src/main/java/dev/latvian/mods/kubejs/misc/MobEffectBuilder.java
Labels: enhancement, 1.18, small change

#274 1.18: Fix speed change for entities - #273
  common/src/main/java/dev/latvian/mods/kubejs/entity/LivingEntityJS.java
Labels: bug, priority: medium

#319 Added more functions for ItemBuilder
  common/src/main/java/dev/latvian/mods/kubejs/item/ItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/mixin/common/ItemMixin.java
Labels: enhancement, last call, new feature

#320 Add ItemPropertiesEventJS
  common/src/main/java/dev/latvian/mods/kubejs/KubeJSEvents.java
  common/src/main/java/dev/latvian/mods/kubejs/client/KubeJSClientEventHandler.java
  common/src/main/java/dev/latvian/mods/kubejs/item/ItemModelPropertiesEventJS.java
Labels: enhancement, last call, 1.18

#324 Added support for adding attributes to items or entities
  common/src/main/java/dev/latvian/mods/kubejs/BuiltinKubeJSPlugin.java
  common/src/main/java/dev/latvian/mods/kubejs/entity/LivingEntityJS.java
  common/src/main/java/dev/latvian/mods/kubejs/item/ItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/ArmorItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/AxeItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/BasicItemJS.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/HoeItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/PickaxeItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/ShovelItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/SwordItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/misc/BasicMobEffect.java
  common/src/main/java/dev/latvian/mods/kubejs/misc/MobEffectBuilder.java
  common/src/main/resources/kubejs.accesswidener
  fabric/src/generated/resources/kubejs.accesswidener
Labels: enhancement, priority: medium
