Repository KubeJS-Mods/KubeJS, pull requests merged in 2022-05, with the labels that each got.

#342 Feature itembuilder texture layers
  common/src/main/java/dev/latvian/mods/kubejs/generator/AssetJsonGenerator.java
  common/src/main/java/dev/latvian/mods/kubejs/item/ItemBuilder.java
Labels: enhancement, 1.18, small change

#332 Fix #330 - Non [a-z0-9_.-] character in namespace
  common/src/main/java/dev/latvian/mods/kubejs/BuiltinKubeJSPlugin.java
  common/src/main/java/dev/latvian/mods/kubejs/item/ItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/ArmorItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/item/custom/ItemArmorTierEventJS.java
  fabric/src/main/java/dev/latvian/mods/kubejs/mixin/fabric/HumanoidArmorLayerMixin.java
  fabric/src/main/resources/kubejs-fabric.mixins.json
Labels: bug, breaking, last call, priority: high, 1.18

#331 Add callbacks to support more in-depth handling of items using
  common/src/main/java/dev/latvian/mods/kubejs/item/ItemBuilder.java
  common/src/main/java/dev/latvian/mods/kubejs/mixin/common/ItemMixin.java
Labels: enhancement, last call, priority: medium, 1.18

#343 Fixed mob effect not correctly updated
  common/src/main/java/dev/latvian/mods/kubejs/misc/BasicMobEffect.java
Labels: bug, priority: medium, small change

#345 Fix NullPointerException for `properties`
  common/src/main/java/dev/latvian/mods/kubejs/block/predicate/BlockIDPredicate.java
Labels: bug, priority: high, small change

#346 Public properties in BlockIdPredicate
  common/src/main/java/dev/latvian/mods/kubejs/block/predicate/BlockIDPredicate.java
Labels: enhancement, 1.18, small change

#174 Implement LivingEntityDropsExperienceEventJS for forge
  common/src/main/java/dev/latvian/kubejs/KubeJSEvents.java
  forge/src/main/java/dev/latvian/kubejs/entity/forge/LivingEntityDropsExperienceEventJS.java
  forge/src/main/java/dev/latvian/kubejs/forge/KubeJSForge.java
Labels: question, enhancement, api, priority: medium, new feature
