Repository KubeJS-Mods/KubeJS, pull requests merged in 2024-03, with the labels that each got.

#804 FEATURE: Added a CarpetBlockBuilder
  common/src/main/java/dev/latvian/mods/kubejs/BuiltinKubeJSPlugin.java
  common/src/main/java/dev/latvian/mods/kubejs/block/custom/CarpetBlockBuilder.java
Labels: enhancement, 1.19

#803 Fixed Shapeless Recipes ignoring output recipe NBT
  fabric/src/main/java/dev/latvian/mods/kubejs/core/mixin/fabric/ShapedRecipeMixin.java
  fabric/src/main/resources/kubejs-fabric.mixins.json
Labels: 1.19

#798 fix tags export from kubejs export command
  common/src/main/java/dev/latvian/mods/kubejs/core/TagLoaderKJS.java
Labels: 1.20

#799 fix tags export (#798) for 1.20.4
  src/main/java/dev/latvian/mods/kubejs/core/TagLoaderKJS.java
Labels: 1.20
